import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { auth } from '../Firebase'
import { GoogleAuthProvider, signInWithPopup } from 'firebase/auth'
import HomePage from './Home'
import { useAuthState } from "react-firebase-hooks/auth"
const inter = Inter({ subsets: ['latin'] })
import 'bootstrap/dist/css/bootstrap.min.css';
import ColorSchemesExample from './Components/Navbar'
import Navbar from './Components/Navbar'
import NavbarHeading from './Components/Navbar'
import { Button } from 'react-bootstrap'

export default function Home() {

  const [user, loading] = useAuthState(auth)

  const login = () => {
    const provider = new GoogleAuthProvider(); 

    signInWithPopup(auth, provider);                      
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavbarHeading />
      <main className={styles.main}>
        {user ? <HomePage auth={auth} /> : (
          <>
          <h1>SchoolSavior</h1>
          <Button variant='primary' onClick={login}>Login</Button>
          </>
        )}
      </main>
    </>
  )
}
